return {
    "ray-x/lsp_signature.nvim",
    --   -- setup() causes double popups by wrapping LazyVim's handler.
    --   -- Instead, keep the module installed only for the <C-s> toggle in keymaps.lua,
    --   -- and auto-trigger the native LSP signature help when typing '('.
    --   -- The handler opens the popup without stealing cursor focus.
    --   init = function()
    --     -- Override LazyVim's handler after everything's loaded.
    --     -- Sets focus=false so typing doesn't jump into the popup.
    --     vim.api.nvim_create_autocmd("User", {
    --       pattern = "VeryLazy",
    --       once = true,
    --       callback = function()
    --         vim.lsp.handlers["textDocument/signatureHelp"] = vim.lsp.with(
    --           vim.lsp.handlers.signatureHelp,
    --           { border = "rounded", focusable = false, focus = false }
    --         )
    --       end,
    --     })
    --
    --     -- Auto-trigger signature help when typing '(' in insert mode
    --     vim.api.nvim_create_autocmd("InsertCharPre", {
    --       group = vim.api.nvim_create_augroup("sig_auto", { clear = true }),
    --       callback = function()
    --         local col = vim.fn.col(".")
    --         if col > 1 and vim.fn.getline("."):sub(col - 1, col - 1) == "(" then
    --           vim.lsp.buf.signature_help()
    --         end
    --       end,
    --     })
    --   end,
}
