bar {
    # Ensure there is no space after 'pango:'
    font pango:0xProto Nerd Font 10
    position top
    
    # Use the absolute path instead of $HOME
    status_command i3status-rs /home/macho25/.config/i3status-rust/config.toml

    # This ensures the bar is always visible
    mode dock
    modifier None

    colors {
        background #1e1e2e
        statusline #cdd6f4
        separator  #45475a

        # Catppuccin Mocha Colors
        focused_workspace  #89b4fa #89b4fa #11111b
        active_workspace   #313244 #313244 #cdd6f4
        inactive_workspace #1e1e2e #1e1e2e #a6adc8
        urgent_workspace   #f38ba8 #f38ba8 #11111b
    }
}
