
# Spotify
bindsym $mod+u exec --no-startup-id ~/.local/bin/spotify_control play-pause
# bindsym $mod+u exec --no-startup-id touch ~/i3_test_file
# --- VIM-STYLE SPOTIFY MODE ---
set $mode_spotify   Spotify: [h]Prev [l]Next [k]Vol+ [j]Vol- [r]Loop [s]Stop [Space]Play/Pause
bindsym $mod+m mode "$mode_spotify"

mode "$mode_spotify" {
    # Navigation (Vim keys)
    bindsym l exec --no-startup-id ~/.local/bin/spotify_control next
    bindsym h exec --no-startup-id ~/.local/bin/spotify_control prev
    
    # Volume (Vim k--no-startup-id eys)
    bindsym k exec --no-startup-id ~/.local/bin/spotify_control inc
    bindsym j exec --no-startup-id ~/.local/bin/spotify_control dec
    
    # Features
    bindsym r exec --no-startup-id ~/.local/bin/spotify_control loop
    bindsym s exec --no-startup-id ~/.local/bin/spotify_control stop
    bindsym Space exec --no-startup-id ~/.local/bin/spotify_control play-pause

    # Exit Mode
    bindsym Return mode "default"
    bindsym Escape mode "default"
    bindsym $mod+m mode "default"
}
