# default i3 tiling mode:
workspace_layout default

#border indicator on windows:
new_window pixel 1

# thin borders
# hide_edge_borders both

# Set inner/outer gaps
gaps inner 15 
gaps outer 10
smart_gaps on

# window title alignment
#title_align center

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# bind program to workspace and focus to them on startup:
assign [class="alacritty"] $ws1
# assign [class="(?i)firefox"] $ws2
assign [class="discord"] $ws9
assign [class="(?i)spotify"] $ws0
assign [class="gaming"] $ws5

# automatic set focus new window if it opens on another workspace than the current:
for_window [class=alacritty] focus
for_window [class=(?i)firefox] focus
for_window [class=discord] focus
for_window [class=(?i)spotify] focus
for_window [class=gaming] focus

##################
# floating rules #
##################

# set floating (nontiling) for apps needing it
for_window [class="Yad" instance="yad"] floating enable
for_window [class="Galculator" instance="galculator"] floating enable
for_window [class="Blueberry.py" instance="blueberry.py"] floating enable

# set floating (nontiling) for special apps
for_window [class="Xsane" instance="xsane"] floating enable
for_window [class="Pavucontrol" instance="pavucontrol"] floating enable
for_window [class="qt5ct" instance="qt5ct"] floating enable
for_window [class="Blueberry.py" instance="blueberry.py"] floating enable
for_window [class="Bluetooth-sendto" instance="bluetooth-sendto"] floating enable
for_window [class="Pamac-manager"] floating enable
for_window [window_role="About"] floating enable

# set border of floating window
for_window [class="urxvt"] border pixel 1

